###############################################################################
#
#    Trey, Kilobytes de Soluciones
#    Copyright (C) 2024-Today Trey, Kilobytes de Soluciones <www.trey.es>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
{
    'name': 'Accont mass reconcile method statement line',
    'summary': (
        'Adds a mass reconciliation method that searches for journal entries '
        'generated by bank statement lines and automatically assigns a '
        'counterpart account based on a configured filter that matches the '
        'bank statement concept.'
    ),
    'author': 'Trey (www.trey.es)',
    'website': 'https://www.trey.es',
    'license': 'AGPL-3',
    'category': 'Account',
    'version': '16.0.1.1.0',
    'depends': [
        'account_mass_reconcile',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/account_mass_reconcile_views.xml',
        'views/account_mass_reconcile_method_views.xml',
    ],
    'images': [
        'static/description/banner.png',
    ],
}
