###############################################################################
# For copyright and license notices, see __manifest__.py file in root directory
###############################################################################
from odoo import api, fields, models


class PurchaseOrder(models.Model):
    _inherit = 'purchase.order'

    is_customer_send = fields.Boolean(
        string='Customer send',
        compute='_compute_is_customer_send',
        store=True,
        help='Indicates whether the purchase order was generated by a route '
             'marked as \'Customer send\' on a sales line of the associated '
             'sales order.',
    )
    sale_id = fields.Many2one(
        comodel_name='sale.order',
        string='Sale order',
    )
    customer_shipping_id = fields.Many2one(
        comodel_name='res.partner',
        string='Delivery address',
    )
    customer_order_ref = fields.Char(
        string='Customer reference',
    )

    @api.depends('order_line', 'sale_id', 'sale_id.order_line.route_id')
    def _compute_is_customer_send(self):
        for purchase in self:
            if purchase.sale_id and purchase.sale_id.order_line:
                for purchase_line in purchase.order_line:
                    if purchase_line.move_dest_ids:
                        sale_lines = purchase_line.move_dest_ids.mapped(
                            'sale_line_id')
                        routes = sale_lines.mapped('route_id')
                        if any(routes.mapped('is_customer_send')):
                            purchase.is_customer_send = True
                            break
            else:
                purchase.is_customer_send = False
