###############################################################################
# For copyright and license notices, see __manifest__.py file in root directory
###############################################################################
from odoo import api, fields, models


class PurchaseOrder(models.Model):
    _inherit = 'purchase.order'

    is_supplier_send = fields.Boolean(
        string='Supplier send',
        compute='_compute_is_supplier_send',
        store=True,
        help='Indicates whether the purchase order was generated by a route '
             'marked as \'Supplier send\' on a sales line of the associated '
             'sales order.',
    )
    sale_id = fields.Many2one(
        comodel_name='sale.order',
        string='Sale order',
    )

    @api.depends('order_line', 'sale_id', 'sale_id.order_line.route_id')
    def _compute_is_supplier_send(self):
        for purchase in self:
            if purchase.sale_id and purchase.sale_id.order_line:
                for purchase_line in purchase.order_line:
                    if purchase_line.move_dest_ids:
                        sale_lines = purchase_line.move_dest_ids.mapped(
                            'sale_line_id')
                        routes = sale_lines.mapped('route_id')
                        if any(routes.mapped('is_supplier_send')):
                            purchase.is_supplier_send = True
                            break
            else:
                purchase.is_supplier_send = False
