###############################################################################
# For copyright and license notices, see __manifest__.py file in root directory
###############################################################################
from odoo import fields, models


class UtmMedium(models.Model):
    _inherit = 'utm.medium'

    quotation_count = fields.Integer(
        string='Quotation Count',
        compute='_compute_quotation_count',
        compute_sudo=True,
        groups='sales_team.group_sale_salesman',
    )
    invoiced_amount = fields.Integer(
        string='Revenues generated by the medium',
        compute='_compute_sale_invoiced_amount',
        compute_sudo=True,
        groups='sales_team.group_sale_salesman',
    )
    company_id = fields.Many2one(
        comodel_name='res.company',
        string='Company',
        readonly=True,
        default=lambda self: self.env.company,
    )
    currency_id = fields.Many2one(
        comodel_name='res.currency',
        related='company_id.currency_id',
        string='Currency',
    )
    use_leads = fields.Boolean(
        string='Use Leads',
        compute='_compute_use_leads',
    )
    crm_lead_count = fields.Integer(
        string='Leads/Opportunities count',
        groups='sales_team.group_sale_salesman',
        compute='_compute_crm_lead_count',
    )

    def _compute_quotation_count(self):
        quotation_data = self.env['sale.order']._read_group(
            [('medium_id', 'in', self.ids)],
            ['medium_id'],
            ['medium_id'],
        )
        data_map = {
            datum['medium_id'][0]: datum['medium_id_count']
            for datum in quotation_data
        }
        for medium in self:
            medium.quotation_count = data_map.get(medium.id, 0)

    def _compute_sale_invoiced_amount(self):
        self.env['account.move.line'].flush_model([
            'balance',
            'move_id',
            'account_id',
            'display_type',
        ])
        self.env['account.move'].flush_model([
            'state',
            'medium_id',
            'move_type',
        ])
        query = """
            SELECT move.medium_id, -SUM(line.balance) as price_subtotal
            FROM account_move_line line
            INNER JOIN account_move move ON line.move_id = move.id
            WHERE move.state not in ('draft', 'cancel')
                AND move.medium_id IN %s
                AND move.move_type IN (
                    'out_invoice', 'out_refund', 'in_invoice',
                    'in_refund', 'out_receipt', 'in_receipt'
                )
                AND line.account_id IS NOT NULL
                AND line.display_type = 'product'
            GROUP BY move.medium_id
        """
        self._cr.execute(query, [tuple(self.ids)])
        query_res = self._cr.dictfetchall()
        mediums = self.browse()
        for datum in query_res:
            medium = self.browse(datum['medium_id'])
            medium.invoiced_amount = datum['price_subtotal']
            mediums |= medium
        for medium in (self - mediums):
            medium.invoiced_amount = 0

    def _compute_use_leads(self):
        self.use_leads = self.env.user.has_group('crm.group_use_lead')

    def _compute_crm_lead_count(self):
        lead_data = self.env['crm.lead'].with_context(
            active_test=False
        )._read_group(
            [('medium_id', 'in', self.ids)],
            ['medium_id'],
            ['medium_id'],
        )
        mapped_data = {
            datum['medium_id'][0]: datum['medium_id_count']
            for datum in lead_data
        }
        for medium in self:
            medium.crm_lead_count = mapped_data.get(medium.id, 0)

    def action_redirect_to_quotations(self):
        action = self.env['ir.actions.actions']._for_xml_id(
            'sale.action_quotations_with_onboarding'
        )
        action['domain'] = [('medium_id', '=', self.id)]
        action['context'] = {'default_medium_id': self.id}
        return action

    def action_redirect_to_invoiced(self):
        action = self.env['ir.actions.actions']._for_xml_id(
            'account.action_move_journal_line'
        )
        invoices = self.env['account.move'].search([
            ('medium_id', '=', self.id)
        ])
        action['context'] = {
            'create': False,
            'edit': False,
            'view_no_maturity': True,
        }
        action['domain'] = [
            ('id', 'in', invoices.ids),
            ('move_type', 'in', (
                'out_invoice', 'out_refund', 'in_invoice',
                'in_refund', 'out_receipt', 'in_receipt'
            )),
            ('state', 'not in', ['draft', 'cancel']),
        ]
        return action

    def action_redirect_to_leads_opportunities(self):
        view = (
            'crm.crm_lead_all_leads' if self.use_leads
            else 'crm.crm_lead_opportunities'
        )
        action = self.env['ir.actions.act_window']._for_xml_id(view)
        action['view_mode'] = 'tree,kanban,graph,pivot,form,calendar'
        action['domain'] = [('medium_id', 'in', self.ids)]
        action['context'] = {'active_test': False, 'create': False}
        return action
